CREATE TRIGGER checktuoi_them_NV ON NHANVIEN FOR INSERT AS
IF (SELECT (YEAR(GETDATE())-YEAR(NGSINH)) FROM inserted) <= 65 AND (SELECT (YEAR(GETDATE())-YEAR(NGSINH)) FROM inserted) >= 18
BEGIN
PRINT N'ĐỘ TUỔI PHẢI NẰM TRONG KHOẢNG 18<= TUỔI =>65'
ROLLBACK TRANSACTION
END