CREATE TRIGGER checkSLdean_ofNV ON DEAN AFTER DELETE AS
BEGIN
DECLARE @SLDEAN INT;
SET @SLDEAN = (SELECT COUNT(*) FROM DEAN, NHANVIEN WHERE DEAN.PHONG = NHANVIEN.PHG)
SELECT @SLDEAN = COUNT(*) FROM deleted
PRINT N'TỔNG SỐ LƯỢNG ĐỀ ÁN MÀ NHÂN VIÊN ĐÃ LÀM LÀ' + @SLDEAN
END